spring:
  profiles:
    default: dev
    #active: dev
    active: prod
  #main:
    #banner-mode: "off"
  output:
    ansi:
      enabled: always
#logging:
 # level:
    #root: WARN
    #root: DEBUG
  jpa:
    show-sql: true #показ sql-запросов
    hibernate:
      ddl-auto: update
